### ISSUE TITLE
Page builder widgets + Beaver Builder

### ISSUE THREAD

**Issue by cantoute** [Codeinwp/themeisle-companion#313]
Hi,

hoping this is the place for Orbit Fox

When activating the plugin with the option "Page builder widgets" and using page builder lte I get this in my logs...

Hoping this could help

A module with the filename class-themeisle-content-forms-beaver-contact.php already exists! Please namespace your module filenames to ensure compatibility with Beaver Builder.
A module with the filename class-themeisle-content-forms-beaver-newsletter.php already exists! Please namespace your module filenames to ensure compatibility with Beaver Builder.
A module with the filename class-themeisle-content-forms-beaver-registration.php already exists! Please namespace your module filenames to ensure compatibility with Beaver Builder.

**Comment by ineagu** [comment]
cc @cristian-ungureanu @contactashish13

**Comment by poonam279** [comment]
Same issue reported here: https://secure.helpscout.net/conversation/1093798773/218167?folderId=212385

**Comment by rodica-andronache** [comment]
@cristian-ungureanu with the new OBFX version from https://github.com/Codeinwp/themeisle-companion/pull/454 I installed Beaver Builder( Lite ) and created a page with OBFX's modules ( Pricing, Posts Grid, etc ).
Switched to Beaver Builder Pro and the modules on the page turned into the corresponding ones from Beaver Builder Pro. For example, `Post Grid from OBFX` turned into `Posts from Beaver Builder`. Is that how it's supposed to work?
![Screenshot (2)](https://user-images.githubusercontent.com/3266155/79358025-66aa5300-7f49-11ea-9883-bf2da49c9d12.png)

**Comment by cristian-ungureanu** [comment]
@rodica-andronache unfortunately yes. I think that's how it works even now. As I said, we are using the same IDs that Beaver Builder Pro is using. When you switch to Beaver Builder Pro, they already have a "post-grid" widget so they'll load theirs. The only thing I can do is to no longer load "post-grid" widget in lite when there are new users and to load "obfx-post-grid" ( which is the same widget but with the id changed )

**Comment by rodica-andronache** [comment]
@cristian-ungureanu from what I understood, I'm not sure if the check for a new user is correct here https://github.com/Codeinwp/themeisle-companion/pull/454/commits/c8d73688b775c00e0f3f9069dd6a1b021c761c67

I've installed OBFX > activated Beaver > created a page with the Post Grid widget from OBFX > activated Beaver Pro -> the Post Grid widget was replaced with the Posts widget from Beaver, because I've done it under 60 seconds.

If I do the same thing and wait a bit between steps, the widget does not get replaced.

In both cases, I thought I'm a new user. Let me know if I'm missing something

**Comment by cristian-ungureanu** [comment]
@rodica-andronache it should work now

**Comment by rodica-andronache** [comment]
@cristian-ungureanu sorry, but I'm still not sure how it should work for new/old users.

If I do the process "installed OBFX > activated Beaver > created a page with the Post Grid widget from OBFX > activated Beaver Pro" without any waiting time, the Post Grid from OBFX is NOT replaced with the one from Beaver 

If I do the same process, with a waiting time of 1 minute after installing OBFX , the Post Grid from OBFX is replaced with the one from Beaver 

Does this mean that a new user is considered only if they install Beaver immediately after installing OBFX ( under 1 minute )?

**Comment by cristian-ungureanu** [comment]
@rodica-andronache there is an option that is set to recognize the new/old user. Its name is obfx_new_user. Please clear that and try to test again. Probably it was already set on the instance you are working so the latest change I've made didn't count. Maybe try it on a new instance on jurassic.ninja
I'll try to better explain the problem and the solution so you'll know how it works and what results to expect.

### What was wrong
Beaver Builder (Lite or Pro) takes the name of the file where you write the widget and make it the id of the widget.
In OBFX old version we add 3 widgets that already exist in Beaver Builder Pro so if you activate Beaver Builder Pro and OBFX it will result in some error logs on the server saying that the widget is already declared.

### The solution
Duplicate the files where widgets are written and prefix them with "obfx".
There are multiple cases to cover:
1. Old user + Beaver Builder Lite => Load the widgets without "obfx" prefix so they won't lose the content they had.
2. Old user + Beaver Builder Lite and he upgraded to Pro => The widgets will be replaced by the one in Beaver Builder Pro ( this is the behavior right now in the OBFX, without this update, except the fact that without the update the widgets from OBFX are not even shown in the widgets list )
3. New user + Beaver Builder Lite => Load the widgets with "obfx" prefix so when the update to Beaver Builder Pro happens there will be no naming conflict.
4. New user + Beaver Builder Lite that upgrades to Pro => The widgets will be the same as they were added in the Lite version, this is the normal case and how it should've worked if there wasn't any naming conflict.

A new user is considered someone that activated the plugin for the first time. In SDK we register the time when a user activates the plugin. Then we get the time at the init hook. We make the difference $current_time - $install_time_form_sdk. If it's lower or equal than 60 seconds it means that that's a new user. We set an option named 'obfx_new_user' with the value 'yes' or 'no' and that option won't change after the code is executed ( that's why the last modification didn't work for you )
